import { SECONDS_PER_MINUTE, MILLISECONDS_PER_SECOND } from "./time.js";

const OAUTH_EXCHANGE_EXPIRY = // 10 minutes
  10 * SECONDS_PER_MINUTE * MILLISECONDS_PER_SECOND;

//   1 day
const TOKEN_EXPIRY = 24 * 60 * SECONDS_PER_MINUTE * MILLISECONDS_PER_SECOND;

export {OAUTH_EXCHANGE_EXPIRY, TOKEN_EXPIRY}

